export const projects = [
  {
    title: 'Personal Portafolio',
    description: "Personal protafolio proyect.",
      image: '/images/1.png',
      tags: ['React', 'NextJs', 'Styled components'],
    source: 'https://github.com/mabsboza/portafolio_webside',
    visit: 'https://marcos-boza-portafolio.vercel.app',
    id: 0,
  },
  {
    title: 'Communitary blog',
    description:"Communitary blog as Reddit, the main idea is create tech content and share knowledge.",
      image: '/images/2.png',
      tags: ['Ruby', 'Ruby on rails, javaScript', 'Bootstrap'],
    source: 'https://github.com/mabsboza/james_code_blog',
    visit: 'https://lets-take-a-coffee.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Covid Info Page',
    description: "This is a information page for Covid, collects statistical and informative data for people. ",
      image: '/images/3.jpg',
      tags: ['Css', 'NextJs, html'],
    source: 'https://github.com/mabsboza/covid',
    visit: 'https://pandemia.vercel.app/',
    id: 2,
  },
  {
    title: 'Podcast',
    description: "This is a mini project to listen podcast from audioboom api.",
      image: '/images/4.jpg',
      tags: ['React', 'NextJs'],
    source: 'https://github.com/mabsboza/podcast',
    visit: 'https://nextjs-podcast-ten.vercel.app/',
    id: 3,
  },
  {
    title: 'Aragro',
    description: "Manage your farm like a company, increase your profits and invest in what really matters.",
      image: '/images/5.jpg',
      tags: ['React', 'Ruby', 'TypeScript', 'Graphql','Postgres'],
    source: 'https://aragro.app/es',
    visit: 'https://aragro.app/es',
    id: 4,
  },
  {
    title: 'Ksec',
    description: "Único sistema de gestión integral de procesos asociados a personal externo, contratistas, transportistas, subcontratados y sus trabajadores.",
      image: '/images/6.jpg',
      tags: ['React', 'TypeScript', 'Tailwind', 'Redux toolkit & RTK Query'],
    source: 'https://www.ksec.cl/',
    visit: 'https://www.ksec.cl/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Worked as a full stack developer (Java/C#/asp.net)', },
  { year: 2017, text: 'Worked as a Semi senior Java developer', },
  { year: 2018, text: 'Changed tech stack and started working in a startup', },
  { year: 2020, text: 'Co-founded Binarios', },
  { year: 2021, text: 'working on making dreams come true ', },
];